development:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock 
  database: db_development
  username: kaneko_development
  password: Hiromasa529

test:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock 
  database: db_test
  username: kaneko_test
  password: Hiromasa529

production:
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: 5
  socket: /var/run/mysqld/mysqld.sock
  database: db_production
  username: kaneko_production
  password: "-Hiromasa529"